spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/hotel
    username: postgres
    password: 60757692@Lmo
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate.format_sql: true
    open-in-view: false
  flyway:
    enabled: true
    locations: classpath:db/migration

logging:
  level:
    org.hibernate.SQL: OFF
    org.hibernate.type.descriptor.sql.BasicBinder: OFF
    org.hibernate.engine.jdbc.spi.SqlStatementLogger: OFF

